parameters:
#    nfq_venick.example.class: Nfq\NfqVenickBundle\Example

services:
#    nfq_venick.example:
#        class: %nfq_venick.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
