<?php

namespace Nfq\NfqVenickBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * weTaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class weTaskRepository extends EntityRepository
{
}
