parameters:
#    nfq_user.example.class: Nfq\UserBundle\Example

services:
#    nfq_user.example:
#        class: %nfq_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
