nfq_wedrive_base:
    pattern:  /
    defaults: { _controller: NfqWeDriveBundle:Base:index }

nfq_wedrive_observer:
    pattern:  /public
    defaults: { _controller: NfqWeDriveBundle:Base:observer }

nfq_wedrive_route_list:
    pattern:  /route/list
    defaults: { _controller: NfqWeDriveBundle:Route:list }

nfq_wedrive_route_new:
    pattern: /route/new
    defaults: { _controller: NfqWeDriveBundle:Route:newRoute }

nfq_wedrive_route_manage:
    pattern:  /route/manage/{routeId}
    defaults: { _controller: NfqWeDriveBundle:Route:manage }

nfq_wedrive_route_delete:
    pattern:  /route/delete/{routeId}
    defaults: { _controller: NfqWeDriveBundle:Route:delete }
    requirements:
        routeId: \d+

nfq_wedrive_trip_list:
    pattern:  /trip/list
    defaults: { _controller: NfqWeDriveBundle:Trip:userTripList }

nfq_wedrive_trip_new:
    pattern:  /trip/new/{routeId}
    defaults:  { _controller: NfqWeDriveBundle:Trip:newTrip }
    requirements:
        routeId: \d+

nfq_wedrive_route_trip_new:
    pattern:  /route/trip/new
    defaults:   { _controller: NfqWeDriveBundle:Trip:newRouteTrip }

nfq_wedrive_trip_manage:
    pattern:  /trip/manage/{tripId}
    defaults:   { _controller: NfqWeDriveBundle:Trip:manageTrip }

nfq_wedrive_trip_join:
    pattern:  /trip/join/{tripId}
    defaults:   { _controller: NfqWeDriveBundle:Trip:joinTrip }

nfq_wedrive_trip_delete:
    pattern:  /trip/delete/{tripId}
    defaults:   { _controller: NfqWeDriveBundle:Trip:deleteTrip }

nfq_wedrive_passenger_list:
    pattern:  /passenger/list/{tripId}
    defaults: { _controller: NfqWeDriveBundle:Passenger:list }

nfq_wedrive_passenger_join_accept:
    pattern:  /passenger/accept/{passengerId}
    defaults:   { _controller: NfqWeDriveBundle:Passenger:acceptPassenger }

nfq_wedrive_passenger_join_reject:
    pattern:  /passenger/reject/{passengerId}
    defaults:   { _controller: NfqWeDriveBundle:Passenger:rejectPassenger }

nfq_wedrive_passenger_join_leave:
    pattern:  /passenger/leave/{passengerId}
    defaults:   { _controller: NfqWeDriveBundle:Passenger:leaveTrip }

nfq_wedrive_notification_seen:
    pattern:  /notification/seen/{notificationId}
    defaults:   { _controller: NfqWeDriveBundle:Notification:seen }

nfq_wedrive_ajax_notifications_show:
    pattern:  /ajax/notification/show
    defaults:   { _controller: NfqWeDriveBundle:Notification:showNotificationList}

nfq_wedrive_ajax_trip_join:
    pattern:  /ajax/trip/join/{tripId}
    defaults: { _controller: NfqWeDriveBundle:Trip:joinTrip }

nfq_wedrive_ajax_availableTrip_list:
    pattern:  /ajax/trip/available
    defaults: { _controller: NfqWeDriveBundle:Trip:availableTripList }

nfq_wedrive_ajax_joinedTrip_list:
    pattern:  /ajax/trip/joined
    defaults: { _controller: NfqWeDriveBundle:Trip:joinedTripList }


