nfq_wedrive_base:
    pattern:  /
    defaults: { _controller: NfqWeDriveBundle:Base:index }

nfq_wedrive_route_list:
    pattern:  /route/list
    defaults: { _controller: NfqWeDriveBundle:Route:list }

nfq_wedrive_route_delete:
    pattern:  /route/delete/{routeId}
    defaults: { _controller: NfqWeDriveBundle:Route:delete }

nfq_wedrive_trip_list:
    pattern:  /trip/list
    defaults: { _controller: NfqWeDriveBundle:Trip:list }

#page for test
nfq_wedrive_test_page:
    pattern:  /test
    defaults: { _controller: NfqWeDriveBundle:Test:index }
