<?php

namespace Nfq\WeDriveBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Nfq\WeDriveBundle\Constants\PassengerState;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{
    /**
     * @param Passenger $passenger
     * @returns string
     */
    public function getMessage(Passenger $passenger){
        $message = "";
        switch ($passenger->getAccepted()) {
            case PassengerState::ST_JOINED:
                $message = str_replace('##PASSENGER_NAME##',
                    $passenger->getUser()->getUsername(),
                    PassengerState::MSG_JOINED);
                break;

            case PassengerState::ST_CANCELED_BY_PASSENGER:
                $message = str_replace('##PASSENGER_NAME##',
                    $passenger->getUser()->getUsername(),
                    PassengerState::MSG_CANCELED_BY_PASSENGER);
                break;

            case PassengerState::ST_CANCELED_BY_DRIVER:
                $message = str_replace('##DRIVER_NAME##',
                    $passenger->getTrip()->getRoute()->getUser()->getUsername(),
                    PassengerState::MSG_CANCELED_BY_DRIVER);
                break;

            case PassengerState::ST_REJECTED_BY_DRIVER:
                $message = str_replace('##DRIVER_NAME##',
                    $passenger->getTrip()->getRoute()->getUser()->getUsername(),
                    PassengerState::MSG_REJECTED_BY_DRIVER);
                break;
        }

        return $message;
    }
}
