<?php

namespace Nfq\WeDriveBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Nfq\UserBundle\Entity\User;
use Nfq\WeDriveBundle\Constants\PassengerState;

/**
 * PassengerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PassengerRepository extends EntityRepository
{
    /**
     * @param User $user
     * @return array|Passenger[]
     */
    public function getPassengersWithRequest(User $user)
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery(
            "
                            SELECT p
                            FROM Nfq\WeDriveBundle\Entity\Passenger p
                            JOIN p.trip t
                            JOIN t.route r
                            JOIN r.user u
                            WHERE u.username = :username and p.accepted = :accepted
                        "
        )->setParameters(array('username'=>$user->getUsername(), 'accepted'=>PassengerState::ST_JOINED));

        $passengers = $query->getResult();

        return $passengers;
    }
}
