<?php

namespace Nfq\WeDriveBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Nfq\UserBundle\Entity\User;

/**
 * PassengerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PassengerRepository extends EntityRepository
{
    /**
     * @param User $user
     * @return array|Passenger[]
     */
    public function getPassengersWithRequest(User $user)
    {
//        SELECT p.*
//        FROM Trip t
//        JOIN Route r ON t.route_id = r.id
//        JOIN fos_user u ON r.user_id = u.id
//        JOIN Passenger p ON t.id = p.trip_id
//        WHERE u.username = 'Daiva'
//            and p.accepted = 1

        $em = $this->getEntityManager();

        $query = $em->createQuery(
            "
                            SELECT p
                            FROM Nfq\WeDriveBundle\Entity\Passenger p
                            JOIN p.trip t
                            JOIN t.route r
                            JOIN r.user u
                            WHERE u.username = :username and p.accepted = 1
                        "
        )->setParameter('username', $user->getUsername());

        $passengers = $query->getResult();

        return $passengers;
    }
}
