<?php

namespace Nfq\WeDriveBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RoutePointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoutePointRepository extends EntityRepository
{
}
